### ISSUE TITLE
Discover local dependencies outside of immediate node_modules

### ISSUE THREAD

**Issue by nolanlawson** [google/tachometer#215]
I really hope that I'm just missing something obvious, so please close this issue if I just misread the documentation or something.

Let's say I have a very simple module with a single `index.js` that I want to test. If I have this in my `tachometer.json`:

```json
{
  "benchmarks": [
    {
      "url": "./benchmark.html",
      "expand": [
        {
          "name": "this-change"
        },
        {
          "name": "tip-of-tree",
          "packageVersions": {
            "label": "tip-of-tree",
            "dependencies": {
              "my-package-name": {
                "kind": "git",
                "repo": "https://github.com/org/my-package-name.git",
                "ref": "master"
              }
            }
          }
        }
      ]
    }
  ]
}
```

And then I use this in my `benchmark.html`:

```js
import myPackage from 'my-package-name'
```

This actually works for the remote dependency, but it doesn't work for the local dependency. Instead, Tachometer doesn't transform the `import` statement, so the browser can't find the module.

![Screenshot from 2021-07-02 14-54-52](https://user-images.githubusercontent.com/283842/124332189-bb81bb80-db45-11eb-9b1d-7a938f73bc7c.png)

Here is [a small repro](https://gist.github.com/nolanlawson/85bdba522731e3fd7d7f4e5d4cf2233f).

The only solution I've found is to manually add symlinks so that `node_modules/my-package-name` is linked locally:

    ln -s .. node_modules/repro-tach-dependency

Then Tachometer works as expected - the local dependency is resolved locally, and the remote one is resolved by fetching it from npm.

I've also observed this issue in a monorepo, where the project structure is like this:

```
packages/my-package-name
packages/my-package-name/index.js
packages/benchmark
packages/benchmark/benchmark.html
```

In this case, if `benchmark.html` tries to do `import 'my-package-name'`, it won't resolve locally.

This might have something to do with subtleties of dependency hoisting. In a monorepo project _without_ dependency hoisting, `packages/benchmark/node_modules` would indeed contain the `my-package-name` package. But in the case I ran into, dependency hoisting moves all the dependencies to the top-level `node_modules`, so Tachometer can't find it, because it seems to check only the immediate `node_modules` directory.

The solution I've found is again to do the `node_modules` symlinking, e.g.:

    ln -s ../../my-package-name ./packages/benchmark/node_modules/my-package-name

To solve both these issues (if this is indeed an issue and I didn't just misconfigure something), it seems to me that the Tachometer module resolver should:

- search for packages at the root level via `package.json` (for the simple single-package case)
- search recursively up the tree for `node_modules` (for the hoisted monorepo case)

Thanks for reading this far, and thanks for creating Tachometer! It's a great tool, and I can use it just fine with the symlinking workaround, but I thought I'd report the issue in case others ran into it or I missed something. :slightly_smiling_face:

**Comment by nolanlawson** [comment]
I wrote [a better repro](https://github.com/nolanlawson/repro-tach-resolve-issue) of the issue.

After a bit of debugging, it seems that [`koa-node-resolve`](https://github.com/Polymer/koa-node-resolve) correctly resolves `some-package`  to `../node_modules/some-package`, but then at some point this gets transformed into `<rootDir>/node_modules/some-package/dist/index.js`, which is wrong because it should be ``<rootDir>/../node_modules/some-package/dist/index.js``. My hunch is that Koa is refusing to serve files outside of the directory that the server is being run from.

The workaround for now still seems to be to put your `tachometer.json` file at the root level – not in a subdirectory. Or, do the `ln` hack above.

**Comment by nolanlawson** [comment]
After thinking about this more deeply, I think this can be solved with:

- `root` (as described here: https://github.com/google/tachometer/issues/244#issuecomment-2267191898)
- not referring to your own package as a bare `'my-package-name'` but instead as e.g. `'./index.js'`

I'm not sure why the resolution works differently for remote vs local tests, but in any case, Tachometer is probably right that it would be weird to resolve `'my-package-name'` to the current directory when running inside the `my-package-name` directory itself. For example, this doesn't work in Node:

```sh
mkdir foo
cd foo
npm init --yes
node -e "require('foo')" # Error: Cannot find module 'foo'
```

So since the resolution doesn't work in plain Node, you wouldn't really expect it to work in Tachometer either. So referring to your own local package as e.g. `'./index.js'` makes a lot more sense.

As for the monorepo issue, I think this is the same as #244 and can be resolved with `root`. Closing this issue. Sorry for the noise!

**Comment by nolanlawson** [comment]
For the record, this issue was actually trickier to resolve than I thought. I'll put a summary here in case it helps anyone else.

Situation: you have a package, e.g. `my-package`, and you want to test the local branch versus a remote (e.g. `main`). There is no monorepo; you want to test a single package and have Tachometer swap it out.

Resolution: use a placeholder package in your `package.json`:

```json
"devDependencies": {
  "@scope/placeholder": "file:."
}
```

Then import from that placeholder in your benchmark scripts:

```js
import foo from '@scope/placeholder'
```

Then tell Tachometer to swap out the placeholder package when resolving the `main` branch dependency:

```json
  "expand": [
    {
      "name": "this-change"
    },
    {
      "name": "tip-of-tree",
      "packageVersions": {
        "label": "tip-of-tree",
        "dependencies": {
          "@scope/placeholder": {
            "kind": "git",
            "repo": "https://github.com/scope/package.git",
            "ref": "main"
          }
        }
      }
    }
  ]
```

It's a little gnarly, but it works! Note the `@scope` to avoid accidental [dependency confusion](https://medium.com/@alex.birsan/dependency-confusion-4a5d60fec610) attacks.

**Comment by jlukic** [comment]
Had this issue in my monorepo was able to fix it using just importmaps which simplified things quite a bit.

```html
// in bench
<script type="importmap">
{
  "imports": {
    "@my-scope/name": "/packages/name/src/index.js",
    // etc
  }
}
</script>
```

Needs `resolveBareModules: false` in the config and root but everything worked great after that. 
```javascript
{
  "root": "../../../..", // path to root
  "resolveBareModules": false,
}
```
